title: VARoadstter Solutions Consulting
description: A modern website using a green color scheme.
url: https://varoadstter.github.io
baseurl: ""
# theme: minima
author:
  name: Hal Darby
  email: varoadstter@gmail.com
social:
  twitter: your_actual_twitter_handle
  github: your_actual_github_username
  linkedin: your_actual_linkedin_profile
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - .gitignore
include:
  - assets
markdown: kramdown
highlighter: rouge
permalink: pretty
defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: default